services:

  zookeeper:
    image: zookeeper
    volumes:
      - './data/zoo/data:/data'
      - './data/zoo/datalog:/datalog'

  ch1:
    image: clickhouse/clickhouse-server:25.4.5
    restart: on-failure
    depends_on:
      - zookeeper
    volumes:
      - './dictionaries:/opt/dictionaries/'
      - './ch_configs/macros_ch1.xml:/etc/clickhouse-server/config.d/macros.xml'
      - './ch_configs:/etc/clickhouse-server/'
    ports:
      - 9000:9000
      - 8123:8123
      - 9440:9440
      - 8443:8443
    ulimits:
      nofile: 262144
    networks:
      - clicknet
    environment:
      CLICKHOUSE_DB: my_database
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin123
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1

  ch2:
    image: clickhouse/clickhouse-server:25.4.5
    restart: on-failure
    depends_on:
      - zookeeper
    volumes:
      - './dictionaries:/opt/dictionaries/'
      - './ch_configs/macros_ch2.xml:/etc/clickhouse-server/config.d/macros.xml'
      - './ch_configs:/etc/clickhouse-server/'
    ulimits:
      nofile: 262144
    networks:
      - clicknet

  ch3:
    image: clickhouse/clickhouse-server:25.4.5
    restart: on-failure
    depends_on:
      - zookeeper
    volumes:
      - './dictionaries:/opt/dictionaries/'
      - './ch_configs/macros_ch3.xml:/etc/clickhouse-server/config.d/macros.xml'
      - './ch_configs:/etc/clickhouse-server/'
    ulimits:
      nofile: 262144
    networks:
      - clicknet

  ch4:
    image: clickhouse/clickhouse-server:25.4.5
    restart: on-failure
    depends_on:
      - zookeeper
    volumes:
      - './ch_configs/macros_ch4.xml:/etc/clickhouse-server/config.d/macros.xml'
      - './dictionaries:/opt/dictionaries/'
      - './ch_configs:/etc/clickhouse-server/'
    ulimits:
      nofile: 262144
    networks:
      - clicknet

  client:
    image: clickhouse/clickhouse-client:21.3.20
    volumes:
      - './client-config.xml:/etc/clickhouse-client/config.xml'
    networks:
      - clicknet

networks:
  clicknet:
    driver: bridge
